### ISSUE TITLE
N64 compatibility list missing game

### ISSUE THREAD

**Issue by SwirlyStone5877** [Flumpster/flumpster.github.io#5]
Tried multiple bases, seen [here](https://github.com/stuff-by-3-random-dudes/UWUVCI-AIO-WPF/issues/54). 

Game Name: At [this issue](https://github.com/stuff-by-3-random-dudes/UWUVCI-AIO-WPF/issues/54).
Region: At [this issue](https://github.com/stuff-by-3-random-dudes/UWUVCI-AIO-WPF/issues/54).
Host Game: Excitebike 64 US didn't work, about to try F-Zero X US.
Status: Didn't work
Notes: Same as the ones in [this issue](https://github.com/stuff-by-3-random-dudes/UWUVCI-AIO-WPF/issues/54).

**Comment by SwirlyStone5877** [comment]
Host Game: F-Zero X US didn't work, about to try Mario Golf US.
Status: Didn't work
Notes: Same as the others.

**Comment by SwirlyStone5877** [comment]
Please let me know if you don't want me to post updates for every single base tried.

**Comment by ZestyTS** [comment]
The community drives the compatibility list, so it depends on what someone tested and tried. If you want to add changes to the list, you can make a fork and make the changes yourself. If that's too complicated, you can write in a single comment all of the things you tested for what's working or not working because every time you comment, you are notifying all of the people who have worked on this.

**Comment by SwirlyStone5877** [comment]
Got it. Thanks!

**Comment by SwirlyStone5877** [comment]
Yeah, so no base or setting works. The only thing that loaded was the VC menu.
